### ISSUE TITLE
Navigation Bar

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-11/chatty-butterworts#1]
## User Story
As a user, when I navigate to your site, I should see a navbar.

## AC
**Given** A user navigates to your page
**Then** they should see a navbar
**And** it should have an application logo
**And** it should have an input field
**And** it should have a clear button
**And** it should remain at the top of the screen if the page scrolls

## Dev Notes
+ use a bootstrap navbar that has a logo, an input field and a dropdown menu
+ on the dropdown menu there should be an option for Dark, Large, and Clear
+ above those dropdown options are checkboxes for each user
+ for the input field, include a button addon labeled submit:
```
<div class="input-group mb-3">
  <input type="text" class="form-control" placeholder="Write a Message" aria-label="chat-message" aria-describedby="button-addon2">
  <div class="input-group-append">
    <button class="btn btn-outline-secondary" type="button" id="button-addon2">Submit</button>
  </div>
</div>
```

**Comment by AaronLain** [comment]
For the dropdown menu use this bootstrap code:
```
<div class="accordion" id="accordionExample">
  <div class="card">
    <div class="card-header" id="headingOne">
      <h2 class="mb-0">
        <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          Collapsible Group Item #1
        </button>
      </h2>
    </div>

    <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
      <div class="card-body">
        <div class="user-radio-buttons"> USER buttons go here</div>
        <div class="option-buttons">Option buttons go here</div>
      </div>
    </div>
  </div>
</div>
```

**Comment by stephencastaneda** [comment]
<img width="564" alt="Screen Shot 2020-03-09 at 7 35 04 PM" src="https://user-images.githubusercontent.com/59769978/76268795-4518c600-623d-11ea-9b9d-ad6905affed2.png">
