### ISSUE TITLE
Large Text

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-11/chatty-butterworts#15]
## User Story
As a user, with tired eyes, I should be able to chat with large text.

## AC
**Given** A user navigates to your page
**Then** they should see a checkbox below the input field called "Large Text"
**And** they should be able to click this checkbox
**And** when the checkbox is selected all the message text should be larger

## Dev Notes
?????

**Comment by stephencastaneda** [comment]
-Radio button should be under the text field with an id of `large-text`
- The radio button should have an event listener that calls the function `bigText`
- This function should add a class use the jQuery `.addClass()` method 
- In css file there should a class `bigFont` that changes the font size to `60 px`
