### ISSUE TITLE
Display Message

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-11/chatty-butterworts#17]
## User Story
As a user, when the page loads, I should see messages.

## AC
**Given** A user navigates to your page
**Then** they should see the 5 messages from `helpers/data/messageData.js`
**And** when they add messages it should add them to the list

## Dev Notes
- create a setter method called `setUserMessages`
- create a function called `userMessageCardBuilder`
- Use the getter method to get `userMessages` array from `helpers/data/messageData.js`
- Import printToDom from `utils.js`
- Build domString and use string interperalation to get values from the array `${message.name}` + `${message.id}` + `{message.text}` + `{message.timeStamp}`
- `${message.name}` will be the card header field in bootstrap card
- `${message.timeStamp}` will replace the card-title field in boostrap card
- `${message.text}` will replace the card-text field in bootstrap card
- `${message.id}` will be added to the bootstrap button 
- call the function `userMessageCardBuilder` in `main.js`

- add ids to the text inputs on navigation 
- use jQuery selector and .val to get inputs
- reprint to Dom

**Comment by stephencastaneda** [comment]
<img width="474" alt="Screen Shot 2020-03-09 at 7 37 52 PM" src="https://user-images.githubusercontent.com/59769978/76268892-b35d8880-623d-11ea-9596-9a252ed8ae57.png">

**Comment by stephencastaneda** [comment]
Use these boostrap cards to print messages:
```<div class="card">
  <h5 class="card-header">Featured</h5>
  <div class="card-body">
    <h5 class="card-title">Special title treatment</h5>
    <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
</div>
```
