### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-11/chatty-butterworts#2]
## User Story
As a user, with sensitive eyes, I should be able to chat using a dark theme.

## AC
**Given** A user navigates to your page
**Then** they should see a checkbox below the input field called "Dark Theme"
**And** they should be able to click this checkbox
**And** when the checkbox is selected the page should show a dark theme with lightly colored text

## Dev Notes
+ create a theme ```@mixin``` that toggles a dark theme when the switch is triggered.
+ ```@mixin``` is set to switch to dark mode by changing sass variables when the checkbox is checked.
+ create a function called ```themeChanger``` that places or removes a ```dark``` attribute to the apps container div

**Comment by AaronLain** [comment]
Use this Bootstrap switch:
```
<div class="custom-control custom-switch">
  <input type="checkbox" class="custom-control-input" id="customSwitch1">
  <label class="custom-control-label" for="customSwitch1">Toggle this switch element</label>
</div>
```
